### ISSUE TITLE
Update the SSL Cert on the http://firepear.net domain

### ISSUE THREAD

**Issue by njones** [firepear/qsplit#3]
When I try to `go get firepear.net/qsplit` it fails to install because the SSL certificate for **firepear.net** expired JAN-4-2017, then when I try to `go get github.com/firepear/qsplit` this fails because it expects to import from "firepear.net/qsplit" due to the import comment.

We can use `go get -insecure firepear.net/qsplit` to install the library, however I thought you should be made aware that the cert has expired. Also, this may break some automated tools that don't have `-insecure` built in.

**Comment by firepear** [comment]
Thanks! I recently reimaged my webserver and forgot to automate the letsencrypt cert renewal.

The cert should now be valid.
